export const questions = [
  {
    id: "Entered",
    title: "You Played",
    condition: "Enter The Website",
    difficulty: "Easy",
    status: false,
    dispatchType: "TYPE_ACHIEVEMENTS_ENTERED",
    isUnlocked: false,
    claimStatus: false,
  },
  {
    id: "2",
    title: "You Answered A Treasure Level Question",
    condition: "Answered A Treasure Level Question",
    difficulty: "Normal",
    status: false,
    dispatchType: "",
    isUnlocked: false,
    claimStatus: false,
  },
  {
    id: "3",
    title: "You Correctly Answered A Treasure Level Question",
    condition: "Correctly Answered A Treasure Level Question",
    difficulty: "Extreme",
    status: false,
    dispatchType: "",
    isUnlocked: false,
    claimStatus: false,
  },
];
